import { useEffect, useRef, useState } from 'react';
import { Check, ChevronRight, Clipboard, Download, FileAudio, Github, Globe2, Languages, Link2, LoaderCircle, Play, Sparkles, Trash2, Upload, X } from 'lucide-react';
import { getJob, submitFile, submitUrl } from './services/api';
import './App.css';
const supported = ['mp3','wav','m4a','aac','ogg','flac','mp4','mov','mkv','webm','avi','mpeg','mpg'];
const languages = ['English','Spanish','French','German','Portuguese','Hindi','Japanese','Korean','Chinese (Simplified)','Arabic','Italian','Russian','Turkish','Indonesian'];
const formatSize = (n) => n < 1024**2 ? `${(n/1024).toFixed(1)} KB` : `${(n/1024**2).toFixed(1)} MB`;
const time = n => `${String(Math.floor(n/60)).padStart(2,'0')}:${String(Math.floor(n%60)).padStart(2,'0')}`;
function App() {
 const [mode,setMode]=useState('file'), [file,setFile]=useState(null), [url,setUrl]=useState(''), [translate,setTranslate]=useState(false), [target,setTarget]=useState('English'), [job,setJob]=useState(null), [error,setError]=useState(''), [drag,setDrag]=useState(false); const input=useRef();
 const choose = item => { if (!item) return; const ext=item.name.split('.').pop().toLowerCase(); if(!supported.includes(ext)){setError(`Unsupported file type. Choose: ${supported.join(', ')}.`);return;} setError('');setFile(item);setMode('file'); };
 const validUrl = value => { try { const parsed=new URL(value); return ['http:','https:'].includes(parsed.protocol); } catch { return false; } };
 const jobId = job?.job_id; const jobStatus = job?.status;
 const start = async () => { setError(''); if(mode==='file'&&!file) return setError('Select an audio or video file first.'); if(mode==='url'&&!validUrl(url)) return setError('Enter a valid HTTP or HTTPS media URL.'); try { const response=mode==='file' ? await submitFile(file,translate,target) : await submitUrl(url.trim(),translate,target); setJob(response.data); } catch(e) { setError(e.response?.data?.detail || 'Could not reach the API. Check that the FastAPI server is running.'); } };
 useEffect(()=>{ if(!jobId || ['completed','failed'].includes(jobStatus)) return; const poll=setInterval(async()=>{try {const {data}=await getJob(jobId);setJob(data)} catch {setError('Lost connection while checking this job.');clearInterval(poll)}},1800); return()=>clearInterval(poll);},[jobId,jobStatus]);
 const result=job?.result; const copy = value => navigator.clipboard.writeText(value).catch(()=>setError('Clipboard access was unavailable.'));
 const download = (name, content, type='text/plain') => {const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
 return <div className="app"><header><a className="brand" href="#top"><span><Sparkles size={18}/></span>LangTrans<span className="accent">-AI</span></a><nav><a href="#workspace">Workspace</a><a href="#about">About</a><a aria-label="GitHub repository" href="https://github.com/Sushma-1706/LangTrans-AI" target="_blank" rel="noreferrer"><Github size={18}/></a><button className="nav-cta" onClick={()=>document.querySelector('#workspace').scrollIntoView({behavior:'smooth'})}>Start transcribing <ChevronRight size={16}/></button></nav></header>
 <main id="top"><section className="hero"><div className="eyebrow"><Sparkles size={14}/> AUDIO & VIDEO INTELLIGENCE</div><h1>Turn every conversation into <em>actionable intelligence.</em></h1><p>Transcribe, translate into the language you choose, and extract structured insights from audio and video in one AI-powered workspace.</p><div className="trust"><span><Check/> Multilingual Whisper</span><span><Check/> Timestamped results</span><span><Check/> Secure server-side processing</span></div></section>
 <section id="workspace" className="workspace"><div className="section-label">01 / CREATE ANALYSIS</div><h2>Bring your media to life.</h2><p className="sub">Choose an upload or a public media link. Your job runs asynchronously, so you can follow every real processing stage.</p><div className="tabs"><button className={mode==='file'?'active':''} onClick={()=>setMode('file')}><Upload size={17}/> Upload file</button><button className={mode==='url'?'active':''} onClick={()=>setMode('url')}><Link2 size={17}/> Paste URL</button></div>
 {mode==='file'?<div className={`dropzone ${drag?'drag':''} ${file?'selected':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);choose(e.dataTransfer.files[0])}} onClick={()=>input.current.click()}><input ref={input} type="file" accept="audio/*,video/*" onChange={e=>choose(e.target.files[0])}/>{file?<><div className="file-icon"><FileAudio/></div><div><b>{file.name}</b><small>{file.type || 'Media file'} · {formatSize(file.size)}</small></div><button className="icon-btn" onClick={e=>{e.stopPropagation();setFile(null)}} aria-label="Remove selected file"><X/></button></>:<><div className="upload-icon"><Upload/></div><b>Drop audio or video here, or <u>browse files</u></b><small>MP3, WAV, M4A, MP4, MOV, MKV, WEBM and more · Max 500 MB</small></>}</div>:<div className="url-field"><Globe2/><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://youtube.com/watch?v=... or direct media URL"/><span>{validUrl(url)?<Check className="valid"/>:null}</span></div>}
 <div className="options"><div><div className="option-title"><Languages size={18}/> Translation</div><p>Keep the original transcript and add a translated version.</p></div><label className="switch"><input type="checkbox" checked={translate} onChange={e=>setTranslate(e.target.checked)}/><span/></label></div>{translate&&<div className="language-row"><label htmlFor="target">Translate into</label><select id="target" value={target} onChange={e=>setTarget(e.target.value)}>{languages.map(l=><option key={l}>{l}</option>)}</select></div>}
 {error&&<div className="alert">{error}<button onClick={()=>setError('')}><X size={16}/></button></div>}<button className="primary" disabled={job&&!['completed','failed'].includes(job.status)} onClick={start}>{job&&!['completed','failed'].includes(job.status)?<LoaderCircle className="spin"/>:<Play size={17}/>} {job&&!['completed','failed'].includes(job.status)?'Processing media…':'Start processing'}</button></section>
 {job&&<section className={`job-card ${job.status}`}><div className="job-top"><div><span className="section-label">LIVE JOB</span><h3>{job.status==='failed'?'Something needs attention':job.status==='completed'?'Analysis complete':'Working on your media'}</h3><p>{job.message}</p></div><span className="status-pill">{job.status.replaceAll('_',' ')}</span></div><div className="progress"><i style={{width:`${job.progress}%`}}/></div><div className="job-meta"><span>Job ID: <code>{job.job_id}</code></span><strong>{job.progress}%</strong></div>{job.error&&<p className="job-error">{job.error}</p>}</section>}
 {result&&<section className="results"><div className="results-heading"><div><div className="section-label">02 / RESULTS</div><h2>{result.summary.title}</h2><p>Detected speech: <b>{result.transcript.language}</b>{result.translation?` · Translated to ${result.translation.language}`:''}</p></div><div className="exports"><button onClick={()=>copy(result.transcript.segments.map(s=>`[${time(s.start)}] ${s.text}`).join('\n'))}><Clipboard/> Copy transcript</button><button onClick={()=>download('langtrans-result.json',JSON.stringify(job,null,2),'application/json')}><Download/> JSON</button></div></div><div className="summary-grid"><article className="summary-lead"><span>AI SUMMARY</span><h3>{result.summary.title}</h3><p>{result.summary.key_points[0]||'No key points were returned for this recording.'}</p></article>{[['Key points',result.summary.key_points],['Topics',result.summary.topics],['Action items',result.summary.action_items],['Keywords',result.summary.keywords]].map(([title,items])=><article className="summary-card" key={title}><h3>{title}</h3>{items.length?<ul>{items.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p>None identified.</p>}</article>)}</div>{result.summary.quotes.length>0&&<article className="quotes"><h3>Notable quotes</h3>{result.summary.quotes.map((quote,i)=><blockquote key={i}>“{quote}”</blockquote>)}</article>}<div className={result.translation?'transcript-grid':'single-transcript'}><Transcript title={`Original transcript · ${result.transcript.language}`} segments={result.transcript.segments} onDownload={()=>download('transcript.txt',result.transcript.segments.map(s=>`[${time(s.start)} – ${time(s.end)}] ${s.text}`).join('\n'))}/>{result.translation&&<Transcript title={`Translation · ${result.translation.language}`} segments={result.translation.segments} onDownload={()=>download('translation.txt',result.translation.segments.map(s=>`[${time(s.start)} – ${time(s.end)}] ${s.text}`).join('\n'))}/>}</div></section>}</main><footer id="about">Built for clearer conversations, in every language. <span>Groq Whisper + Llama · In-memory job history clears on backend restart.</span></footer></div> }
function Transcript({title,segments,onDownload}) {return <article className="transcript"><div><h3>{title}</h3><button onClick={onDownload}><Download size={15}/> TXT</button></div><div className="segment-list">{segments.length?segments.map((s,i)=><p key={i}><time>{time(s.start)}</time><span>{s.text}</span></p>):<p className="empty">No transcript segments available.</p>}</div></article>}
export default App;
